# Generated by Django 3.0.4 on 2021-06-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomy', '0002_sequencetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencetest',
            name='file',
            field=models.FileField(blank=True, upload_to='datafolder'),
        ),
    ]
