# Generated by Django 3.0.4 on 2021-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anatomy', '0004_testhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='H',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
